name = "aoc2024"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
file_streams = ">= 1.2.3 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
shine_tree = ">= 0.0.6 and < 1.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleamy_structures = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
